# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

# This job is allowed to fail as will default to fuse
apiVersion: batch/v1
kind: Job
metadata:
  name: shiftfs-module-loader-{{repl Cursor }}
  labels:
    app: gitpod
    component: shiftfs-module-loader
spec:
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 30
  backoffLimit: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: gitpod
        component: shiftfs-module-loader
    spec:
      serviceAccountName: installer
      restartPolicy: Never
      containers:
        - name: shiftfs-module-loader
          # This is the current valid tag. This will be auto-updated by the Werft job
          image: eu.gcr.io/gitpod-core-dev/build/shiftfs-module-loader:commit-37164c872f55851dbd8126e1b5a8c062bc36fc1b
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /usr/src_node
              name: node-linux-src
              readOnly: true
      volumes:
        - name: node-linux-src
          hostPath:
            path: /usr/src
            type: Directory
