---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: installation-status
  labels:
    app: gitpod
    component: gitpod-installer-status
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitpod-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: installation-status
  labels:
    app: gitpod
    component: gitpod-installer-status
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitpod-registry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: installer-12
  labels:
    app: gitpod
    component: gitpod-installer
    cursor: "12"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitpod-registry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shiftfs-module-loader-12
  labels:
    app: gitpod
    component: shiftfs-module-loader
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitpod-registry
